---
title: A QC tool for openCyto
output: rmarkdown::html_vignette
always_allow_html: yes
vignette: >
  %\VignetteIndexEntry{cytoqc-kw}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
# cytoqc -- qc for keywords


```{r include=FALSE}
library(knitr)
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```


```{r}
library(flowCore)
library(flowWorkspace)
library(cytoqc)
```

```{r include=FALSE}
# prepare the test data
data("GvHD")
fs <- GvHD
data_dir <- tempfile()
dir.create(data_dir)
write.flowSet(fs, data_dir)
```

## Load the FCS

```{r}
files <- list.files(data_dir, ".fcs", full.names = TRUE)
cqc_data <- cqc_load_fcs(files)
cqc_data
```

```{r include=FALSE}
#clean up keywordnames
for(cf in cqc_data)
{
  kw <- keyword(cf)
  kn <- names(kw)
  kn <- gsub("^\\&[0-9]+", "", kn)
  names(kw) <- kn
  keyword(cf) <- kw
  
}
#simulate channel discrepancy

#case
cf <- cqc_data[[1]]
cf_keyword_rename(cf, "Patient ID",  "patient id")

#missing
cf <- cqc_data[[2]]
cf_keyword_delete(cf, "Patient ID")


#redundant
cf <- cqc_data[[1]]
cf_keyword_insert(cf, "new_kw", "test")


#typo
cf <- cqc_data[[3]]
kw <- keyword(cf)
kn <- names(kw)
cf_keyword_rename(cf, "Patient ID",  "PatientId")



```

## Group by keywords
```{r}
groups <- cqc_check(cqc_data, "keyword")
groups

```

## Match against reference and report the discrepancy
```{r}
match_result <- cqc_match(groups, ref = 2)
match_result
```


## Inspect the content of the two keywords that are likely to be semantically the same
```{r}
sub_data_ref <- cqc_get_data(groups, id = 2)
unique(sapply(sub_data_ref, keyword, keyword = "Patient ID"))

sub_data <- cqc_get_data(groups, id = 4)
unique(sapply(sub_data, keyword, keyword = "pt name"))

```

##  Manually match them if they are considered to be the same
```{r}
match_result <- cqc_update_match(match_result, c("pt name" = "Patient ID"))
match_result
```

## Apply the fix

```{r}
cqc_fix(match_result)
```

## Refresh QC report 
```{r}
groups <- cqc_check(cqc_data, "keyword")
groups
```

## Check the difference
```{r}
res <- cqc_match(groups, ref = 1)
res
```

## split into two groups if they can't be merged
```{r}
grps <- split(groups)
grps
```



