context("cqc_check")
path <- "~/remote/fh/fast/gottardo_r/mike_working/lyoplate_out/parsed"

skip_if_not(dir.exists(path))

centers <- c('BIIR','CIMR','Miami','NHLBI','Stanford','UCLA','Yale')

##load gs
panel <- "tcell"
test_results <- test_results_all[[panel]]
# test_results <- list()
gslist <- sapply(centers, function(center) {
  # message("Center: ", center)
  gs <- load_gs(file.path(path, center, panel), select = 1)
})

cqc_data <- list()
test_that("cqc_gs_list", {
  cqc_data <<- cqc_gs_list(gslist)
  names(cqc_data) <<- centers#fix the guid of gs between runs to avoid the random ids generated by boost::uuids::random_generator(), which isn't controled by R set.seed
  expect_is(cqc_data, "cqc_gs_list")
})

test_that("cf_get_panel", {
  cf <- get_cytoframe_from_cs(cqc_data[[1]], 1)
  tbl <- cf_get_panel(cf)
  expect_equal(colnames(tbl), c("channel", "marker"))
  expect_equal(as.vector(tbl[["channel"]]), colnames(cf))
  expect_equal(as.vector(tbl[["marker"]]),as.vector(pData(parameters(cf))[["desc"]]))

})

test_that("cqc_check_gate", {
  test_results_gate <- test_results[["gate"]]

  groups <- cqc_check(cqc_data, "gate")
  expect_is(groups, "cqc_check_gate")
  expect_equal(groups, test_results_gate[["check"]][["result"]])
  expect_equal(summary(groups), test_results_gate[["check"]][["summary"]])
  expect_equal(diff(groups), test_results_gate[["check"]][["diff"]])

  expect_error(cqc_match(cqc_data, ref = 1), "not a valid")
  match_result <- cqc_match(groups, ref = 1)
  expect_equal(match_result, test_results_gate[["match"]][["result"]])#strange that this test fail at package check (but succeed in console)
  expect_equal(match_result_color_tbl(match_result), test_results_gate[["match"]][["match_result_color_tbl"]])

  expect_error(cqc_fix(groups), "not a valid")
  cqc_fix(match_result)
  expect_equal(cqc_check(cqc_data, "gate"), test_results_gate[["check"]][["fixed_result"]])

})

test_that("cqc_check_marker", {
  test_results_marker <- test_results[["marker"]]

  groups <- cqc_check(cqc_data, "marker")
  expect_equal(groups, test_results_marker[["check"]][["result"]])

  match_result <- cqc_match(groups, ref = 3)
  expect_equal(match_result, test_results_marker[["match"]][["result"]])
  expect_equal(format(match_result), test_results_marker[["match"]][["format"]])
  expect_equal(match_result_color_tbl(match_result), test_results_marker[["match"]][["match_result_color_tbl"]])

  match_result <- cqc_update_match(match_result,  map = c("CD197" = "CCR7"))
  expect_equivalent(match_result, test_results_marker[["match"]][["result_update"]])

  cqc_fix(match_result)
  expect_equal(cqc_check(cqc_data, "marker"), test_results_marker[["check"]][["fixed_result"]])

})

test_that("cqc_check_panel", {
  test_results_panel <- test_results[["panel"]]

  groups <- cqc_check(cqc_data, "panel")
  expect_equal(groups, test_results_panel[["check"]][["result"]])
  expect_equal(format(groups), test_results_panel[["check"]][["format"]])
  expect_equal(format(groups, anchor = "marker"), test_results_panel[["check"]][["format_by_marker"]])

  cf <- gs_cyto_data(cqc_data[[1]])[[1]]
  panel <- cf_get_panel(cf, skip_na = TRUE)
  cqc_set_panel(cqc_data, panel, ref.col = "marker")
  groups <- cqc_check(cqc_data, "panel")
  expect_equal(groups, test_results_panel[["check"]][["fixed_result"]])

})

test_that("cqc_check_channel", {
  test_results_channel <- test_results[["channel"]]

  groups <- cqc_check(cqc_data, "channel")
  expect_equal(groups, test_results_channel[["check"]][["result"]])

  match_result <- cqc_match(groups, ref = 4)
  expect_equal(match_result, test_results_channel[["match"]][["result"]])
  expect_equal(format(match_result), test_results_channel[["match"]][["format"]])
  expect_equal(match_result_color_tbl(match_result), test_results_channel[["match"]][["match_result_color_tbl"]])

  cqc_fix(match_result)
  expect_equal(cqc_check(cqc_data, "channel"), test_results_channel[["check"]][["fixed_result"]])

})
